### ISSUE TITLE
How to apply the model to extract terms from a new data set

### ISSUE THREAD

**Issue by H0radricCube** [CooDL/NestedTermExtraction#1]
nevermind XD

**Comment by Gyyz** [comment]
Thanks. It seems the problem of the parameters. But if your data is not in Gene Domain, I think it is better to train a new model instead. I don't think the pre-trained model can make significant domain adaptation.

**Comment by H0radricCube** [comment]
You're right QAQ It seems I'll have to find myself a usable dataset. Thanks!
